### ISSUE TITLE
Closing media queries

### ISSUE THREAD

**Issue by aubreywullschleger** [franklincandanoza/f1-3-c2p1-colmar-academy#1]
Subtlety for errors! Line 376 of your CSS you need a closing curly brace for your media query that starts on line 314, without this curly brace your page looks incomplete.  Be sure to add that in!

https://github.com/franklincandanoza/f1-3-c2p1-colmar-academy/blob/master/Colmar/resources/css/styles.css#L314-L376

**Comment by franklincandanoza** [comment]
done.
