### ISSUE TITLE
Organization of markup

### ISSUE THREAD

**Issue by aubreywullschleger** [franklincandanoza/f1-3-c2p1-colmar-academy#2]
Great! Nice job with the consistent nesting and indentation in your HTML. I would consider implementing semantic elements as this helps improve the accessibility of your page. Here's info on how semantic elements help with accessibility: https://webflow.com/blog/html5-semantic-elements-and-webflow-the-essential-guide (scroll down to the 'So what are semantic elements good for?' heading) and a list of semantic elements you can use: http://www.techstrikers.com/HTML5/html5-semantic-elements.php

Example: https://github.com/franklincandanoza/f1-3-c2p1-colmar-academy/blob/master/Colmar/index.html#L15-L31

**Comment by franklincandanoza** [comment]
thank you
