### ISSUE TITLE
Thesis section

### ISSUE THREAD

**Issue by aubreywullschleger** [franklincandanoza/f1-3-c2p1-colmar-academy#4]
Subtlety for errors!  I would be sure to implement the Thesis section of the spec page.  This requires a little research into how to implement the `<video>` element and will be great to practice.  Check out the documentation for how to implement the `<video>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by franklincandanoza** [comment]
thank you.
