### ISSUE TITLE
Responsive concepts in CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [franklincandanoza/f1-3-c2p1-colmar-academy#5]
Simplify!  Great job using flex-box for your layout and media queries for the responsiveness of your page.  To make your CSS more concise I would use group selectors for any repeated styles like `display: flex;`

Also, I really appreciate the extra effort you put in with the styling choices of your page, particularly your color choices and hover states.

**Comment by franklincandanoza** [comment]
thank you
