### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [franklincandanoza/f1-3-c2p1-colmar-academy#6]
Grade: Meets expectations

Summary:
Overall, great job on this final project! I like your use of locally stored images and that your page is responsive.

A few things to work on would be: 1. making sure you are closing your media queries, 2. using descriptive `alt` attributes, and 3. using group selectors for any repeated styles.

Next, as a stretch goal, I challenge you to build more pages for this site.  What does a sign in page look like? What about a course page?  Building these extra pages will add some complexity, allow you to practice more with flex-box and media queries, and is a challenge I think you are ready for based on your work here!

**Comment by franklincandanoza** [comment]
thank you.
